version: '3.8'
services:
  n8n:
    build:
      context: .
      dockerfile: docker/images/n8n-custom/Dockerfile
    image: n8n-custom
    environment:
      - N8N_SECURE_COOKIE=false
      - DOMAIN_NAME=datafabdevelopment.com
      - SUBDOMAIN=chicago-workflow-dev
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5681
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
    container_name: n8n-custom
    restart: unless-stopped
    networks:
      - app_net
    volumes:
      - n8n_data:/home/node/.n8n 
    expose:
      - "5678"  # Expose port 5678 internally to Nginx, but not to the host

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5681:80"  # Expose Nginx on port 5678 to the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - n8n
    networks:
      - app_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_net:
    driver: bridge

volumes:
  n8n_data:
    driver: local